"""updated tables

Revision ID: 4acd490e025e
Revises: 
Create Date: 2026-01-19 17:13:07.570762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4acd490e025e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vaccine_master')
    op.drop_index(op.f('ix_patient_documents_id'), table_name='patient_documents')
    op.drop_table('patient_documents')
    op.drop_table('patient_vaccine_plan')
    op.drop_index(op.f('ix_patients_district'), table_name='patients')
    op.drop_index(op.f('ix_patients_state'), table_name='patients')
    op.drop_table('patients')
    op.drop_table('vaccine_audit_logs')
    op.drop_table('vaccine_schedule')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vaccine_schedule',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('vaccine_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('dose_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('min_age_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_age_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_booster', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['vaccine_id'], ['vaccine_master.id'], name=op.f('vaccine_schedule_vaccine_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('vaccine_schedule_pkey'))
    )
    op.create_table('vaccine_audit_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('plan_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('old_status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('new_status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('changed_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('changed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], name=op.f('vaccine_audit_logs_changed_by_fkey')),
    sa.ForeignKeyConstraint(['plan_id'], ['patient_vaccine_plan.id'], name=op.f('vaccine_audit_logs_plan_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('vaccine_audit_logs_pkey'))
    )
    op.create_table('patients',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('dob', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('parent_contact', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('district', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('city_or_village', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('pincode', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('Address', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='patients_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_patients_state'), 'patients', ['state'], unique=False)
    op.create_index(op.f('ix_patients_district'), 'patients', ['district'], unique=False)
    op.create_table('patient_vaccine_plan',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('vaccine_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('dose_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('administered_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('verified_by_worker', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('patient_vaccine_plan_patient_id_fkey')),
    sa.ForeignKeyConstraint(['vaccine_id'], ['vaccine_master.id'], name=op.f('patient_vaccine_plan_vaccine_id_fkey')),
    sa.ForeignKeyConstraint(['verified_by_worker'], ['users.id'], name=op.f('patient_vaccine_plan_verified_by_worker_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('patient_vaccine_plan_pkey')),
    sa.UniqueConstraint('patient_id', 'vaccine_id', 'dose_number', name=op.f('uq_patient_vaccine_plan'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('patient_documents',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('document_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('patient_documents_patient_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('patient_documents_pkey'))
    )
    op.create_index(op.f('ix_patient_documents_id'), 'patient_documents', ['id'], unique=False)
    op.create_table('vaccine_master',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('vaccine_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('vaccine_master_pkey')),
    sa.UniqueConstraint('vaccine_code', name=op.f('vaccine_master_vaccine_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
